linters:
  # HTML + ERB formatting
  HtmlBeautifier:
    enabled: true
    auto_correct: true
    indent: 2
    newline_between_tags: true
    remove_trailing_whitespace: true
    recursive: true

  # Ruby code indentation inside ERB
  Indentation:
    enabled: true
    spaces: 2
    auto_correct: true

  # Single space inside ERB tags
  ErbPercentSpacing:
    enabled: true
    enforce_single_space: true
    auto_correct: true

  # Ensure newline after multi-line ERB blocks
  EndNewline:
    enabled: true
    auto_correct: true

  # Ensure file ends with a trailing newline
  TrailingNewline:
    enabled: true
    auto_correct: true

  # Optional: enforce HTML closing tags
  ClosingTag:
    enabled: true
    auto_correct: true

  # Optional: detect empty ERB tags
  EmptyErb:
    enabled: true
    auto_correct: true

# Treat .turbo_stream.erb files as ERB
file_patterns:
  "**/*.turbo_stream.erb": {}

# Exclude unnecessary directories
exclude:
  - "node_modules/**/*"
  - "vendor/**/*"

