AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.1
  SuggestExtensions: false
plugins:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance
Style/Documentation:
  Enabled: false
Rails/ReversibleMigration:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  # keep business logic in the code not the database
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Rails/NotNullColumn:
  # suggests default values on foreign keys
  Enabled: false
Minitest/MultipleAssertions:
  # assertions are good
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/BlockComments:
  # block comments are fine
  Enabled: false
